version: '2'
services:
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ~/Projects/homebridge-config/:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
