version: '2'
services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - /home/jared/Projects/homebridge-config/:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
